// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDviMQoj2nmMl_Yw0BURZMaqZwmox1_cNI',
    appId: '1:808015143618:web:fbf8981db6d00a33d5115b',
    messagingSenderId: '808015143618',
    projectId: 'film-app-008',
    authDomain: 'film-app-008.firebaseapp.com',
    storageBucket: 'film-app-008.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTIn4uxg9RmMzZDEZMpKJp6kWY1s-WXeQ',
    appId: '1:808015143618:android:f8b2b5f62c6c86b3d5115b',
    messagingSenderId: '808015143618',
    projectId: 'film-app-008',
    storageBucket: 'film-app-008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAKnMlJg-QBxWPHAiEBZ5jCueKT6IFG-E',
    appId: '1:808015143618:ios:997498c9b48f04c2d5115b',
    messagingSenderId: '808015143618',
    projectId: 'film-app-008',
    storageBucket: 'film-app-008.appspot.com',
    iosClientId: '808015143618-dkea7lge8cqvcckaeh162e4elmb6k77h.apps.googleusercontent.com',
    iosBundleId: 'com.example.films',
  );
}
